# Generated by Django 5.2.8 on 2025-11-19 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='expenses.monthlybudget'),
        ),
        migrations.AlterField(
            model_name='monthlybudget',
            name='monthly_budget',
            field=models.IntegerField(),
        ),
    ]
